done
JoeManyak/web1 pull request #1
Opened 2021-09-21 19:19 UTC by JoeManyak

2021-09-23 08:27 UTC, nosovk commented on .eslintrc.json
> +  "extends": "metarhia"
sonar lint забыт?

2021-09-23 08:28 UTC, nosovk requested changes

2021-09-23 08:28 UTC, nosovk commented on .husky/pre-commit
> +git add .
не должно быть сайдеффектов в хуках

2021-09-23 08:28 UTC, nosovk commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
это думаю тоже можно в ignore положить?

2021-09-23 08:28 UTC, nosovk commented on index.html
> +    <meta charset="UTF-8" />
забыли viewport

2021-09-23 08:29 UTC, nosovk commented on index.html
> +      <div id="b2" class="block">Картопляне пюре</div>
id is evil, please avoid

2021-09-23 08:29 UTC, nosovk commented on index.html
> +    <div class="wrapper">
html semantic tags?

2021-09-23 08:29 UTC, nosovk commented on index.html
> +    <link rel="stylesheet" href="styles.css" />
absolute links?

2021-09-23 08:29 UTC, nosovk commented on package.json
> +    "test": "eslint .",
lint is not test

2021-09-23 08:30 UTC, nosovk commented on package.json
> +    "test": "eslint .",
eslint should ignore folders specified in .gitignore

2021-09-23 08:30 UTC, nosovk commented on package.json
> +    "format": "prettier --write .",
there should be 2 ways of linters/formaters invocation: intrusive and not. Probably we missing something here

2021-09-23 08:30 UTC, nosovk commented on styles.css
> +  background: #4964ff;
css vars?

2021-09-23 08:31 UTC, nosovk commented
github actions to launch validations?

2021-11-06 16:36 UTC, JoeManyak commented
fixed

2021-11-06 16:38 UTC, closed without merging